// Este archivo contiene configuración, no componentes de React.
// Cada módulo indica sus rutas, filtros, columnas, campos del formulario y detalles.
// Las páginas reutilizables leen esta información para no repetir cuatro veces el mismo código.

const sharedDeliveryFields = [
  { name: 'DeliveryAddressLine1', label: 'Dirección de entrega', maxLength: 60, required: true, section: 'Direcciones' },
  { name: 'DeliveryAddressLine2', label: 'Dirección de entrega (línea 2)', maxLength: 60, section: 'Direcciones' },
  { name: 'DeliveryPostalCode', label: 'Código postal de entrega', maxLength: 10, required: true, section: 'Direcciones' },
  { name: 'PostalAddressLine1', label: 'Dirección postal', maxLength: 60, required: true, section: 'Direcciones' },
  { name: 'PostalAddressLine2', label: 'Dirección postal (línea 2)', maxLength: 60, section: 'Direcciones' },
  { name: 'PostalPostalCode', label: 'Código postal', maxLength: 10, required: true, section: 'Direcciones' },
  { name: 'DeliveryLatitude', label: 'Latitud', type: 'number', min: -90, max: 90, step: '0.000001', section: 'Ubicación' },
  { name: 'DeliveryLongitude', label: 'Longitud', type: 'number', min: -180, max: 180, step: '0.000001', section: 'Ubicación' },
]

export const entities = {
  // Módulo de clientes.
  customers: {
    route: 'clientes',
    title: 'Clientes',
    singular: 'cliente',
    description: 'Gestión de clientes, contactos, entrega y condiciones de pago.',
    idField: 'CustomerID',
    nameField: 'CustomerName',
    filters: [
      { name: 'CustomerName', label: 'Nombre', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
      { name: 'CustomerCategoryID', label: 'Categoría', type: 'select', catalog: 'customerCategories' },
      { name: 'DeliveryMethodID', label: 'Método de entrega', type: 'select', catalog: 'deliveryMethods' },
    ],
    columns: [
      { key: 'CustomerName', label: 'Cliente' },
      { key: 'CustomerCategoryName', label: 'Categoría' },
      { key: 'DeliveryMethodName', label: 'Método de entrega' },
    ],
    formFields: [
      { name: 'CustomerName', label: 'Nombre del cliente', maxLength: 100, required: true, section: 'Información general', fullWidth: true },
      { name: 'CustomerCategoryID', label: 'Categoría', type: 'select', catalog: 'customerCategories', required: true, section: 'Información general' },
      { name: 'BuyingGroupID', label: 'Grupo de compra', type: 'select', catalog: 'buyingGroups', section: 'Información general' },
      { name: 'BillToCustomerID', label: 'Cliente por facturar (opcional)', type: 'select', catalog: 'customers', section: 'Información general' },
      { name: 'PrimaryContactPersonID', label: 'Contacto primario', type: 'select', catalog: 'people', required: true, section: 'Contactos' },
      { name: 'AlternateContactPersonID', label: 'Contacto alternativo', type: 'select', catalog: 'people', section: 'Contactos' },
      { name: 'PhoneNumber', label: 'Teléfono', type: 'tel', maxLength: 20, required: true, section: 'Contactos' },
      { name: 'FaxNumber', label: 'Fax', type: 'tel', maxLength: 20, required: true, section: 'Contactos' },
      { name: 'WebsiteURL', label: 'Sitio web', type: 'url', maxLength: 256, required: true, section: 'Contactos', fullWidth: true },
      { name: 'DeliveryMethodID', label: 'Método de entrega', type: 'select', catalog: 'deliveryMethods', required: true, section: 'Entrega' },
      { name: 'DeliveryCityID', label: 'Ciudad de entrega', type: 'city', labelField: 'DeliveryCityName', required: true, section: 'Entrega' },
      { name: 'PostalCityID', label: 'Ciudad postal', type: 'city', labelField: 'PostalCityName', required: true, section: 'Entrega' },
      { name: 'AccountOpenedDate', label: 'Fecha de apertura', type: 'date', required: true, section: 'Condiciones' },
      { name: 'PaymentDays', label: 'Días para pagar', type: 'number', min: 0, required: true, section: 'Condiciones' },
      { name: 'CreditLimit', label: 'Límite de crédito', type: 'number', min: 0, step: '0.01', section: 'Condiciones' },
      { name: 'StandardDiscountPercentage', label: 'Descuento estándar (%)', type: 'number', min: 0, max: 100, step: '0.001', required: true, section: 'Condiciones' },
      { name: 'IsStatementSent', label: 'Enviar estado de cuenta', type: 'checkbox', section: 'Condiciones' },
      { name: 'IsOnCreditHold', label: 'Crédito suspendido', type: 'checkbox', section: 'Condiciones' },
      ...sharedDeliveryFields,
      { name: 'LastEditedBy', label: 'Editado por (ID)', type: 'number', min: 1, required: true, section: 'Auditoría' },
    ],
    detailSections: [
      { title: 'Información general', fields: ['CustomerID', 'CustomerName', 'CustomerCategoryName', 'BuyingGroupName', 'BillToCustomerID', 'BillToCustomerName'] },
      { title: 'Contactos', fields: ['PrimaryContactPerson', 'AlternateContactPerson', 'PhoneNumber', 'FaxNumber', 'WebsiteURL'] },
      { title: 'Entrega y pago', fields: ['DeliveryMethodName', 'DeliveryCityName', 'DeliveryPostalCode', 'PaymentDays', 'Address'] },
    ],
  },
  // Módulo de proveedores.
  suppliers: {
    route: 'proveedores',
    title: 'Proveedores',
    singular: 'proveedor',
    description: 'Proveedores, referencias bancarias, contactos y logística.',
    idField: 'SupplierID',
    nameField: 'SupplierName',
    filters: [
      { name: 'SupplierName', label: 'Nombre', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
      { name: 'SupplierCategoryID', label: 'Categoría', type: 'select', catalog: 'supplierCategories' },
      { name: 'DeliveryMethodID', label: 'Método de entrega', type: 'select', catalog: 'deliveryMethods' },
    ],
    columns: [
      { key: 'SupplierName', label: 'Proveedor' },
      { key: 'SupplierCategoryName', label: 'Categoría' },
      { key: 'DeliveryMethodName', label: 'Método de entrega' },
    ],
    formFields: [
      { name: 'SupplierName', label: 'Nombre del proveedor', maxLength: 100, required: true, section: 'Información general', fullWidth: true },
      { name: 'SupplierReference', label: 'Código del proveedor', maxLength: 20, required: true, section: 'Información general' },
      { name: 'SupplierCategoryID', label: 'Categoría', type: 'select', catalog: 'supplierCategories', required: true, section: 'Información general' },
      { name: 'PrimaryContactPersonID', label: 'Contacto primario', type: 'select', catalog: 'people', required: true, section: 'Contactos' },
      { name: 'AlternateContactPersonID', label: 'Contacto alternativo', type: 'select', catalog: 'people', required: true, section: 'Contactos' },
      { name: 'PhoneNumber', label: 'Teléfono', type: 'tel', maxLength: 20, required: true, section: 'Contactos' },
      { name: 'FaxNumber', label: 'Fax', type: 'tel', maxLength: 20, required: true, section: 'Contactos' },
      { name: 'WebsiteURL', label: 'Sitio web', type: 'url', maxLength: 256, required: true, section: 'Contactos', fullWidth: true },
      { name: 'DeliveryMethodID', label: 'Método de entrega', type: 'select', catalog: 'deliveryMethods', section: 'Entrega' },
      { name: 'DeliveryCityID', label: 'Ciudad de entrega', type: 'city', labelField: 'DeliveryCityName', required: true, section: 'Entrega' },
      { name: 'PostalCityID', label: 'Ciudad postal', type: 'city', labelField: 'PostalCityName', required: true, section: 'Entrega' },
      { name: 'PaymentDays', label: 'Días para pagar', type: 'number', min: 0, required: true, section: 'Condiciones bancarias' },
      { name: 'BankAccountName', label: 'Nombre de la cuenta bancaria', maxLength: 50, section: 'Condiciones bancarias' },
      { name: 'BankAccountNumber', label: 'Número de cuenta', maxLength: 20, section: 'Condiciones bancarias' },
      { name: 'BankAccountBranch', label: 'Sucursal bancaria', maxLength: 50, section: 'Condiciones bancarias' },
      ...sharedDeliveryFields,
      { name: 'LastEditedBy', label: 'Editado por (ID)', type: 'number', min: 1, required: true, section: 'Auditoría' },
    ],
    detailSections: [
      { title: 'Información general', fields: ['SupplierID', 'SupplierReference', 'SupplierName', 'SupplierCategoryName'] },
      { title: 'Contactos', fields: ['PrimaryContactPerson', 'AlternateContactPerson', 'PhoneNumber', 'FaxNumber', 'WebsiteURL'] },
      { title: 'Entrega', fields: ['DeliveryMethodName', 'DeliveryCityName', 'DeliveryPostalCode', 'Address'] },
      { title: 'Condiciones bancarias', fields: ['BankAccountName', 'BankAccountNumber', 'PaymentDays'] },
    ],
  },
  // Módulo de inventario.
  inventory: {
    route: 'inventario',
    title: 'Inventario',
    singular: 'producto',
    description: 'Productos, existencias, precios, empaque y ubicación física.',
    idField: 'StockItemID',
    nameField: 'StockItemName',
    filters: [
      { name: 'StockItemName', label: 'Producto', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
      { name: 'StockGroupID', label: 'Grupo', type: 'select', catalog: 'stockGroups' },
      { name: 'MinimumQuantityOnHand', label: 'Cantidad mínima', type: 'number', min: 0 },
      { name: 'MaximumQuantityOnHand', label: 'Cantidad máxima', type: 'number', min: 0 },
    ],
    columns: [
      { key: 'StockItemName', label: 'Producto' },
      { key: 'StockGroupName', label: 'Grupo' },
      { key: 'QuantityOnHand', label: 'Disponible', type: 'integer', align: 'end' },
    ],
    formFields: [
      { name: 'StockItemName', label: 'Nombre del producto', maxLength: 100, required: true, section: 'Información general', fullWidth: true },
      { name: 'SupplierID', label: 'Proveedor', type: 'select', catalog: 'suppliers', required: true, section: 'Información general' },
      { name: 'StockGroupID', label: 'Grupo inicial', type: 'select', catalog: 'stockGroups', section: 'Información general', createOnly: true },
      { name: 'ColorID', label: 'Color', type: 'select', catalog: 'colors', section: 'Información general' },
      { name: 'Brand', label: 'Marca', maxLength: 50, section: 'Información general' },
      { name: 'Size', label: 'Talla o tamaño', maxLength: 20, section: 'Información general' },
      { name: 'UnitPackageID', label: 'Unidad de empaque', type: 'select', catalog: 'packageTypes', required: true, section: 'Empaque' },
      { name: 'OuterPackageID', label: 'Empaque exterior', type: 'select', catalog: 'packageTypes', required: true, section: 'Empaque' },
      { name: 'QuantityPerOuter', label: 'Cantidad por empaque', type: 'number', min: 1, required: true, section: 'Empaque' },
      { name: 'LeadTimeDays', label: 'Días de entrega', type: 'number', min: 0, required: true, section: 'Empaque' },
      { name: 'IsChillerStock', label: 'Requiere refrigeración', type: 'checkbox', section: 'Empaque' },
      { name: 'TaxRate', label: 'Impuesto (%)', type: 'number', min: 0, max: 100, step: '0.001', required: true, section: 'Precios' },
      { name: 'UnitPrice', label: 'Precio unitario', type: 'number', min: 0, step: '0.01', required: true, section: 'Precios' },
      { name: 'RecommendedRetailPrice', label: 'Precio de venta recomendado', type: 'number', min: 0, step: '0.01', section: 'Precios' },
      { name: 'TypicalWeightPerUnit', label: 'Peso por unidad', type: 'number', min: 0, step: '0.001', required: true, section: 'Precios' },
      { name: 'QuantityOnHand', label: 'Cantidad disponible', type: 'number', min: 0, required: true, section: 'Existencias' },
      { name: 'BinLocation', label: 'Ubicación', maxLength: 20, required: true, section: 'Existencias' },
      { name: 'LastStocktakeQuantity', label: 'Cantidad en último conteo', type: 'number', min: 0, required: true, section: 'Existencias' },
      { name: 'LastCostPrice', label: 'Último costo', type: 'number', min: 0, step: '0.01', required: true, section: 'Existencias' },
      { name: 'ReorderLevel', label: 'Nivel de reorden', type: 'number', min: 0, required: true, section: 'Existencias' },
      { name: 'TargetStockLevel', label: 'Nivel objetivo', type: 'number', min: 0, required: true, section: 'Existencias' },
      { name: 'Barcode', label: 'Código de barras', maxLength: 50, section: 'Datos adicionales' },
      { name: 'MarketingComments', label: 'Comentarios de marketing', type: 'textarea', section: 'Datos adicionales', fullWidth: true },
      { name: 'LastEditedBy', label: 'Editado por (ID)', type: 'number', min: 1, required: true, section: 'Auditoría' },
    ],
    detailSections: [
      { title: 'Producto', fields: ['StockItemID', 'StockItemName', 'SupplierName', 'ColorName', 'Brand', 'Size'] },
      { title: 'Empaque', fields: ['UnitPackageName', 'OuterPackageName', 'QuantityPerOuter', 'TypicalWeightPerUnit'] },
      { title: 'Precios y existencias', fields: ['TaxRate', 'UnitPrice', 'RecommendedRetailPrice', 'QuantityOnHand', 'BinLocation'] },
      { title: 'Búsqueda', fields: ['KeyWords'] },
    ],
  },
  // Módulo de ventas.
  sales: {
    route: 'ventas',
    title: 'Ventas',
    singular: 'venta',
    description: 'Facturas, clientes, entrega y detalle de productos vendidos.',
    idField: 'InvoiceID',
    nameField: 'CustomerName',
    filters: [
      { name: 'CustomerName', label: 'Cliente', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
      { name: 'InvoiceDateFrom', label: 'Fecha desde', type: 'date' },
      { name: 'InvoiceDateTo', label: 'Fecha hasta', type: 'date' },
      { name: 'MinimumInvoiceAmount', label: 'Monto mínimo', type: 'number', min: 0, step: '0.01' },
      { name: 'MaximumInvoiceAmount', label: 'Monto máximo', type: 'number', min: 0, step: '0.01' },
      { name: 'DeliveryMethodID', label: 'Método de entrega', type: 'select', catalog: 'deliveryMethods' },
    ],
    columns: [
      { key: 'InvoiceID', label: 'Factura' },
      { key: 'InvoiceDate', label: 'Fecha', type: 'date' },
      { key: 'CustomerName', label: 'Cliente' },
      { key: 'DeliveryMethodName', label: 'Método de entrega', responsive: true },
      { key: 'InvoiceAmount', label: 'Monto', type: 'currency', align: 'end' },
    ],
    formFields: [
      { name: 'CustomerID', label: 'Cliente', type: 'select', catalog: 'customers', required: true, section: 'Encabezado' },
      { name: 'BillToCustomerID', label: 'Cliente por facturar', type: 'select', catalog: 'customers', required: true, section: 'Encabezado' },
      { name: 'InvoiceDate', label: 'Fecha de factura', type: 'date', required: true, section: 'Encabezado' },
      { name: 'CustomerPurchaseOrderNumber', label: 'Número de orden del cliente', maxLength: 20, section: 'Encabezado' },
      { name: 'DeliveryMethodID', label: 'Método de entrega', type: 'select', catalog: 'deliveryMethods', required: true, section: 'Entrega' },
      { name: 'ContactPersonID', label: 'Persona de contacto', type: 'select', catalog: 'people', required: true, section: 'Entrega' },
      { name: 'SalespersonPersonID', label: 'Vendedor', type: 'select', catalog: 'people', required: true, section: 'Entrega' },
      { name: 'AccountsPersonID', label: 'Responsable de cuenta', type: 'select', catalog: 'people', required: true, section: 'Entrega' },
      { name: 'PackedByPersonID', label: 'Empacado por', type: 'select', catalog: 'people', required: true, section: 'Entrega' },
      { name: 'DeliveryInstructions', label: 'Instrucciones de entrega', type: 'textarea', section: 'Entrega', fullWidth: true },
      { name: 'Comments', label: 'Comentarios', type: 'textarea', section: 'Notas', fullWidth: true },
      { name: 'IsCreditNote', label: 'Es nota de crédito', type: 'checkbox', section: 'Notas' },
      { name: 'LastEditedBy', label: 'Editado por (ID)', type: 'number', min: 1, required: true, section: 'Auditoría' },
    ],
    detailSections: [
      { title: 'Factura', fields: ['InvoiceID', 'InvoiceDate', 'CustomerName', 'DeliveryMethodName', 'CustomerPurchaseOrderNumber'] },
      { title: 'Personas', fields: ['ContactPerson', 'SalesPerson'] },
      { title: 'Entrega', fields: ['DeliveryInstructions'] },
    ],
  },
}
