export const fieldLabels = {
  CustomerID: 'ID del cliente',
  CustomerName: 'Nombre del cliente',
  CustomerCategoryName: 'Categoría',
  BuyingGroupName: 'Grupo de compra',
  PrimaryContactPerson: 'Contacto primario',
  AlternateContactPerson: 'Contacto alternativo',
  BillToCustomerID: 'ID del cliente por facturar',
  BillToCustomerName: 'Cliente por facturar',
  DeliveryMethodName: 'Método de entrega',
  DeliveryCityName: 'Ciudad de entrega',
  DeliveryPostalCode: 'Código postal',
  PhoneNumber: 'Teléfono',
  FaxNumber: 'Fax',
  PaymentDays: 'Días para pagar',
  WebsiteURL: 'Sitio web',
  Address: 'Dirección',
  SupplierID: 'ID del proveedor',
  SupplierReference: 'Código del proveedor',
  SupplierName: 'Nombre del proveedor',
  SupplierCategoryName: 'Categoría',
  BankAccountName: 'Nombre de la cuenta',
  BankAccountNumber: 'Número de cuenta',
  StockItemID: 'ID del producto',
  StockItemName: 'Nombre del producto',
  ColorName: 'Color',
  Brand: 'Marca',
  Size: 'Talla o tamaño',
  UnitPackageName: 'Unidad de empaque',
  OuterPackageName: 'Empaque exterior',
  QuantityPerOuter: 'Cantidad por empaque',
  TypicalWeightPerUnit: 'Peso por unidad',
  TaxRate: 'Impuesto',
  UnitPrice: 'Precio unitario',
  RecommendedRetailPrice: 'Precio recomendado',
  QuantityOnHand: 'Cantidad disponible',
  BinLocation: 'Ubicación',
  KeyWords: 'Palabras clave',
  InvoiceID: 'Número de factura',
  InvoiceDate: 'Fecha de factura',
  CustomerPurchaseOrderNumber: 'Orden del cliente',
  ContactPerson: 'Persona de contacto',
  SalesPerson: 'Vendedor',
  DeliveryInstructions: 'Instrucciones de entrega',
}
