export const reports = {
  1: {
    title: 'Compras por proveedor',
    shortTitle: 'Compras a proveedores',
    description: 'Montos máximo, mínimo y promedio agrupados por proveedor y categoría.',
    status: 'available',
    filters: [
      { name: 'SupplierName', label: 'Proveedor', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
      { name: 'SupplierCategoryName', label: 'Categoría', maxLength: 50, placeholder: 'Coincidencia en la categoría' },
    ],
    columns: [
      { key: 'SupplierName', label: 'Proveedor' },
      { key: 'SupplierCategoryName', label: 'Categoría' },
      { key: 'MaxSupplierPurchase', label: 'Compra máxima', type: 'currency', align: 'end' },
      { key: 'MinSupplierPurchase', label: 'Compra mínima', type: 'currency', align: 'end' },
      { key: 'AvgSupplierPurchase', label: 'Compra promedio', type: 'currency', align: 'end' },
    ],
  },
  2: {
    title: 'Ventas por cliente',
    shortTitle: 'Ventas a clientes',
    description: 'Montos máximo, mínimo y promedio agrupados por cliente y categoría.',
    status: 'available',
    filters: [
      { name: 'CustomerName', label: 'Cliente', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
      { name: 'CustomerCategoryName', label: 'Categoría', maxLength: 50, placeholder: 'Coincidencia en la categoría' },
    ],
    columns: [
      { key: 'CustomerName', label: 'Cliente' },
      { key: 'CustomerCategoryName', label: 'Categoría' },
      { key: 'MaxAmount', label: 'Venta máxima', type: 'currency', align: 'end' },
      { key: 'MinAmount', label: 'Venta mínima', type: 'currency', align: 'end' },
      { key: 'AvgPurchase', label: 'Venta promedio', type: 'currency', align: 'end' },
    ],
  },
  3: {
    title: 'Top 5 de productos por ganancia',
    shortTitle: 'Productos más rentables',
    description: 'Productos que generan mayor ganancia en ventas por año.',
    status: 'available',
    filters: [
      { name: 'Year', label: 'Año', type: 'select', catalog: 'years' },
      { name: 'StockItemName', label: 'Producto', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
    ],
    columns: [
      { key: 'InvoiceYear', label: 'Año' },
      { key: 'ProfitRank', label: 'Posición', type: 'rank', align: 'center' },
      { key: 'StockItemName', label: 'Producto' },
      { key: 'TotalProfit', label: 'Ganancia total', type: 'currency', align: 'end' },
    ],
  },
  4: {
    title: 'Top 5 de clientes por facturas',
    shortTitle: 'Clientes con más facturas',
    description: 'Clientes con mayor cantidad de facturas y su monto total por año.',
    status: 'available',
    filters: [
      { name: 'Year', label: 'Año', type: 'select', catalog: 'years' },
      { name: 'CustomerName', label: 'Cliente', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
    ],
    columns: [
      { key: 'InvoiceYear', label: 'Año' },
      { key: 'ClientRank', label: 'Posición', type: 'rank', align: 'center' },
      { key: 'CustomerName', label: 'Cliente' },
      { key: 'InvoiceCount', label: 'Facturas', type: 'integer', align: 'end' },
      { key: 'TotalAmount', label: 'Monto total', type: 'currency', align: 'end' },
    ],
  },
  5: {
    title: 'Top 5 de proveedores por órdenes',
    shortTitle: 'Proveedores con más órdenes',
    description: 'Proveedores con mayor cantidad de órdenes de compra por año.',
    status: 'available',
    filters: [
      { name: 'Year', label: 'Año', type: 'select', catalog: 'years' },
      { name: 'SupplierName', label: 'Proveedor', maxLength: 100, placeholder: 'Coincidencia en el nombre' },
    ],
    columns: [
      { key: 'OrderYear', label: 'Año' },
      { key: 'SupplierRank', label: 'Posición', type: 'rank', align: 'center' },
      { key: 'SupplierName', label: 'Proveedor' },
      { key: 'OrderCount', label: 'Órdenes', type: 'integer', align: 'end' },
    ],
  },
  6: {
    title: 'Matriz de ventas por categoría',
    shortTitle: 'Matriz anual de ventas',
    description: 'Resumen de ventas de categorías de productos por año.',
    status: 'available',
    columns: [
      { key: 'StockGroupName', label: 'Categoría de Producto' },
      { key: 'Sales_2013', label: 'Ventas 2013', type: 'currency', align: 'end' },
      { key: 'Sales_2014', label: 'Ventas 2014', type: 'currency', align: 'end' },
      { key: 'Sales_2015', label: 'Ventas 2015', type: 'currency', align: 'end' },
      { key: 'Sales_2016', label: 'Ventas 2016', type: 'currency', align: 'end' },
      { key: 'GrandTotal', label: 'Total General', type: 'currency', align: 'end' },
    ],
  },
  7: {
    title: 'Seguimiento mensual de clientes',
    shortTitle: 'Seguimiento de clientes',
    description: 'Compras mensuales, fechas de facturación y cantidades por cliente.',
    status: 'available',
    filters: [
      { name: 'Year', label: 'Año', type: 'select', catalog: 'years' },
      { name: 'Month', label: 'Mes', type: 'select', catalog: 'months' },
      { name: 'StockGroupName', label: 'Grupo de producto', maxLength: 100, placeholder: 'Coincidencia en el grupo' },
    ],
    columns: [
      { key: 'CustomerName', label: 'Cliente' },
      { key: 'InvoiceYear', label: 'Año' },
      { key: 'InvoiceMonth', label: 'Mes', type: 'month' },
      { key: 'TotalPurchasedAmount', label: 'Total comprado', type: 'currency', align: 'end' },
      { key: 'FirstInvoiceDate', label: 'Primera factura', type: 'date' },
      { key: 'LastInvoiceDate', label: 'Última factura', type: 'date' },
      { key: 'TotalQuantity', label: 'Cantidad total', type: 'integer', align: 'end' },
      { key: 'MinQuantity', label: 'Mínima', type: 'integer', align: 'end' },
      { key: 'MaxQuantity', label: 'Máxima', type: 'integer', align: 'end' },
    ],
  },
  8: {
    title: 'Seguimiento mensual de proveedores',
    shortTitle: 'Seguimiento de proveedores',
    description: 'Compras mensuales, fechas de órdenes y cantidades por proveedor.',
    status: 'available',
    filters: [
      { name: 'Year', label: 'Año', type: 'select', catalog: 'years' },
      { name: 'Month', label: 'Mes', type: 'select', catalog: 'months' },
      { name: 'StockGroupName', label: 'Grupo de producto', maxLength: 100, placeholder: 'Coincidencia en el grupo' },
    ],
    columns: [
      { key: 'SupplierName', label: 'Proveedor' },
      { key: 'OrderYear', label: 'Año' },
      { key: 'OrderMonth', label: 'Mes', type: 'month' },
      { key: 'TotalPurchasedAmount', label: 'Total comprado', type: 'currency', align: 'end' },
      { key: 'FirstOrderDate', label: 'Primera orden', type: 'date' },
      { key: 'LastOrderDate', label: 'Última orden', type: 'date' },
      { key: 'TotalQuantity', label: 'Cantidad total', type: 'integer', align: 'end' },
      { key: 'MinQuantity', label: 'Mínima', type: 'integer', align: 'end' },
      { key: 'MaxQuantity', label: 'Máxima', type: 'integer', align: 'end' },
    ],
  },
  10: {
    title: 'Método de envío favorito por ubicación',
    shortTitle: 'Métodos de envío',
    description: 'Muestra el método de envío favorito según el lugar de la venta, ordenado por cantidad.',
    status: 'available',
    filters: [
      { name: 'Year', label: 'Año', type: 'select', catalog: 'years' },
      { name: 'Month', label: 'Mes', type: 'select', catalog: 'months' },
      { name: 'CustomerCategoryName', label: 'Categoría de cliente', maxLength: 100, placeholder: 'Coincidencia en la categoría' },
      { name: 'StockGroupName', label: 'Categoría de producto', maxLength: 100, placeholder: 'Coincidencia en la categoría' },
      { name: 'StockItemName', label: 'Producto', maxLength: 100, placeholder: 'Coincidencia en el producto' }
    ],
    columns: [
      { key: 'DeliveryCity', label: 'Ciudad' },
      { key: 'DeliveryState', label: 'Estado' },
      { key: 'DeliveryMethodName', label: 'Método de entrega' },
      { key: 'SalesCount', label: 'Cantidad de ventas', type: 'integer', align: 'end' }
    ],
  },
}
